kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-ha-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "2"
   io_profile: "sequential"
   aggregation_level: "3"
   io_priority: "high"
   group: "minio"
