apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: etcd-group-snapshot
  namespace: default
  annotations:
    portworx/snapshot-type: local
    portworx.selector/group-id: etcd
spec:
  persistentVolumeClaimName: data-px-etcd-etcd-0
