kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-basic-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: px-basic-sc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
