kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  name: ns.px-postgres.pvc.px-postgres-snap-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: px-repl3-sc
    px/snapshot-source-pvc: px-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
